# Base configs
baseurl: "https://photos.desentropia.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Julian Alarcon"
subtitle: "A glance of my life in pics!"
author: "Julian Alarcon"
header:
 title: "Photos"
 subtitle: "by Julian Alarcon"
footer:
 name: "Hi! My name is Julian"
 bio: "I'm a Photographer and I am also involved in the Development Software business (as DevOps)<br><br>

I enjoy learning from new cultures and I try to experience one new thing every day, loves
open source and currently involve in Street, Drone, Landscape and Architecture photography.<br><br>

You can contact me using any of the social networks links below.<br><br>

<sub>©2021 - Julian Alarcon - All Rights Reserved.</sub>"
social_urls:
  facebook: "https://www.facebook.com/julian.alarcon.alcuadrado"
  twitter: "https://twitter.com/julian_alarcon_"
  instagram: "https://instagram.com/framingthechaos/"
  linkedin: "https://www.linkedin.com/in/julian-alarcon"
  github: "https://github.com/julian-alarcon/"
